a = 5
b = 10
ans = a + b
print(a,"+",b,"=",ans)
ans = a - b
print(a,"-",b,"=",ans)
ans = a * b
print(a,"*",b,"=",ans)
ans = a / b
print(a,"/",b,"=",ans)
ans = a // b #apcs考試主要使用
print(a,"//",b,"=",ans)
a = 13
b = 10
ans = a // b
print(a,"//",b,"=",ans)
ans = a % b #求餘數
print(a,"%",b,"=",ans)
